# Generated by Django 5.2.16 on 2026-08-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Coché = affiché dans 'Nos climatiseurs populaires' sur la page d'accueil", verbose_name='Populaire'),
        ),
    ]
